---
# All attributes that the ansible.builtin.git module supports may be used
operators_git_repos:
  - repo: https://github.com/openstack-k8s-operators/install_yamls.git
    # don't change this path
    dest: ~/install_yamls
  - repo: https://github.com/openstack-k8s-operators/octavia-operator.git
    dest: ~/octavia-operator
    version: main
  # Optional repositories:
  - repo: https://github.com/openstack-k8s-operators/neutron-operator.git
    dest: ~/neutron-operator
    depth: 10
  - repo: https://github.com/openstack-k8s-operators/lib-common.git
    dest: ~/lib-common
make_crc_cpus: 20
make_crc_memory: 40000
make_crc_disk: 70
